name: "Pull Request Labeler"
permissions:
  actions: read

on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Labeler
        uses: actions/labeler@v6
        with:
          sync-labels: true
