name: Check Commit
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    defaults:
      run:
        working-directory: ${{ matrix.lib }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        run: poetry install
      - name: Check format
        run: poetry run black --check .

  typing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    defaults:
      run:
        working-directory: ${{ matrix.lib }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        run: poetry install
      - name: Check typing
        run: poetry run mypy --install-types --non-interactive --strict $(echo "${{ matrix.lib }}" | tr "-" "_")

  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    defaults:
      run:
        working-directory: ${{ matrix.lib }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          pip install poetry
          poetry --version
      - name: Install dependencies and library
        run: poetry install
      - name: Check security
        run: poetry run bandit -sB105 -r .
