name: Pytest-cov

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  pytest-cov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
        python-version: [ '3.10' ,'3.11', '3.12', '3.13' ]
    defaults:
      run:
        working-directory: ${{ matrix.lib }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies and library
        run: poetry install
      - name: Run tests with coverage
        run: poetry run pytest --cov --cov-report=xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy
      - name: Upload coverage artifact
        if: ${{ matrix.python-version == '3.12' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report-python-${{ matrix.lib }}
          path: ${{ matrix.lib }}/coverage.xml

  upload-coverage-python:
    needs: pytest-cov
    if: ${{ !cancelled() && needs.pytest-cov.result == 'success' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      code-quality: write
    strategy:
      matrix:
        lib:
          - scaleway-core
          - scaleway
          - scaleway-async
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: coverage-report-python-${{ matrix.lib }}
      - uses: actions/upload-code-coverage@v1
        with:
          file: coverage.xml
          language: Python
          label: code-coverage-agent
